### ISSUE TITLE
[BUG] This domain has expired

### ISSUE THREAD

**Issue by inkydragon** [30-seconds/30-seconds-of-python-code#77]
## [BUG] website down

![image](https://user-images.githubusercontent.com/5158738/57349205-d5086200-718b-11e9-9ab2-37ba5597c34b.png)

### Possible Solution
change links to https://kriadmin.github.io/30-seconds-of-python-code/

**Comment by Chalarangelo** [comment]
Yep, the original author and owner of the domain doesn't seem to have been very active lately. I'll see what I can do.

**Comment by inkydragon** [comment]
I think just change this link is enough.
![image](https://user-images.githubusercontent.com/5158738/57351384-4b10c700-7194-11e9-9f0c-cf99dffb04ed.png)

**Comment by Chalarangelo** [comment]
Unfortunately, I cannot change the link as I'm not the owner of the repo. 😕

**Comment by Chalarangelo** [comment]
This problem has been resolved
