### ISSUE TITLE
BUG twitter icon doesn't render

### ISSUE THREAD

**Issue by AngeloGiacco** [30-seconds/30-seconds-of-python-code#78]
This is not a snippet bug. The issue is simply that twitter icon does not render.

The link for the image  - https://jpillora.com/github-twitter-button/img/tweet.png - is outdated and will just redirect to https://github.com/jpillora. 

I'm not sure what the icon looked like before but i'm guessing it was something like this one: https://img.icons8.com/color/48/000000/twitter.png which could be used to fix this problem

**Comment by Chalarangelo** [comment]
We will be migrating to a new infrastructure soon, therefore I am closing this issue, as it will no longer be relevant in the future (ETA: 1 week from now).
